In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/My Drive/healthcare_dataset.csv')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Tiffany Ramirez,81,Female,O-,Diabetes,2022-11-17,Patrick Parker,Wallace-Hamilton,Medicare,37490.983364,146,Elective,2022-12-01,Aspirin,Inconclusive
1,Ruben Burns,35,Male,O+,Asthma,2023-06-01,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064845,404,Emergency,2023-06-15,Lipitor,Normal
2,Chad Byrd,61,Male,B-,Obesity,2019-01-09,Paul Baker,Walton LLC,Medicare,36874.896997,292,Emergency,2019-02-08,Lipitor,Normal
3,Antonio Frederick,49,Male,B-,Asthma,2020-05-02,Brian Chandler,Garcia Ltd,Medicare,23303.322092,480,Urgent,2020-05-03,Penicillin,Abnormal
4,Mrs. Brandy Flowers,51,Male,O-,Arthritis,2021-07-09,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344184,477,Urgent,2021-08-02,Paracetamol,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,James Hood,83,Male,A+,Obesity,2022-07-29,Samuel Moody,"Wood, Martin and Simmons",UnitedHealthcare,39606.840083,110,Elective,2022-08-02,Ibuprofen,Abnormal
9996,Stephanie Evans,47,Female,AB+,Arthritis,2022-01-06,Christopher Yates,Nash-Krueger,Blue Cross,5995.717488,244,Emergency,2022-01-29,Ibuprofen,Normal
9997,Christopher Martinez,54,Male,B-,Arthritis,2022-07-01,Robert Nicholson,Larson and Sons,Blue Cross,49559.202905,312,Elective,2022-07-15,Ibuprofen,Normal
9998,Amanda Duke,84,Male,A+,Arthritis,2020-02-06,Jamie Lewis,Wilson-Lyons,UnitedHealthcare,25236.344761,420,Urgent,2020-02-26,Penicillin,Normal
9999,Eric King,20,Male,B-,Arthritis,2023-03-22,Tasha Avila,"Torres, Young and Stewart",Aetna,37223.965865,290,Emergency,2023-04-15,Penicillin,Abnormal

In [ ]:
# import matplotlib.pyplot as plt
# # Create a histogram
# plt.hist(df, bins=20)

# # Show the plot
# plt.show()

In [4]:
# Counting the number of distinct values in each column of the DataFrame
distinct_value_counts = {col: df[col].nunique() for col in df.columns}
distinct_value_counts

{'Name': 9378,
 'Age': 68,
 'Gender': 2,
 'Blood Type': 8,
 'Medical Condition': 6,
 'Date of Admission': 1815,
 'Doctor': 9416,
 'Hospital': 8639,
 'Insurance Provider': 5,
 'Billing Amount': 10000,
 'Room Number': 400,
 'Admission Type': 3,
 'Discharge Date': 1834,
 'Medication': 5,
 'Test Results': 3}

In [5]:
# Counting the number of unique values in each column of the DataFrame
unique_value_counts = {col: df[col].value_counts().head() for col in df.columns}
unique_value_counts

{'Name': Michael Johnson      7
 James Johnson        6
 Michael Miller       4
 Michelle Williams    4
 Scott Smith          4
 Name: Name, dtype: int64,
 'Age': 59    175
 78    174
 31    172
 20    169
 35    169
 Name: Age, dtype: int64,
 'Gender': Female    5075
 Male      4925
 Name: Gender, dtype: int64,
 'Blood Type': AB-    1275
 AB+    1258
 B-     1252
 O+     1248
 O-     1244
 Name: Blood Type, dtype: int64,
 'Medical Condition': Asthma          1708
 Cancer          1703
 Hypertension    1688
 Arthritis       1650
 Obesity         1628
 Name: Medical Condition, dtype: int64,
 'Date of Admission': 2019-04-12    15
 2022-04-27    15
 2021-10-23    14
 2023-03-27    14
 2022-10-01    14
 Name: Date of Admission, dtype: int64,
 'Doctor': Michael Johnson      7
 Robert Brown         5
 Michelle Anderson    5
 Matthew Smith        5
 Jennifer Smith       5
 Name: Doctor, dtype: int64,
 'Hospital': Smith PLC         19
 Smith and Sons    17
 Smith Ltd         14
 Smith Inc         14
 Johnson PLC       13
 Name: Hospital, dtype: int64,
 'Insurance Provider': Cigna               2040
 Blue Cross          2032
 Aetna               2025
 UnitedHealthcare    1978
 Medicare            1925
 Name: Insurance Provider, dtype: int64,
 'Billing Amount': 37490.983364    1
 33332.570385    1
 19166.455615    1
 26645.338403    1
 45729.371668    1
 Name: Billing Amount, dtype: int64,
 'Room Number': 358    44
 230    40
 257    38
 469    37
 195    36
 Name: Room Number, dtype: int64,
 'Admission Type': Urgent       3391
 Emergency    3367
 Elective     3242
 Name: Admission Type, dtype: int64,
 'Discharge Date': 2021-11-28    14
 2020-10-08    13
 2020-10-18    13
 2022-08-17    13
 2021-03-23    13
 Name: Discharge Date, dtype: int64,
 'Medication': Penicillin     2079
 Lipitor        2015
 Ibuprofen      1976
 Aspirin        1968
 Paracetamol    1962
 Name: Medication, dtype: int64,
 'Test Results': Abnormal        3456
 Inconclusive    3277
 Normal          3267
 Name: Test Results, dtype: int64}

In [6]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
print(df.columns)

Index(['name', 'age', 'gender', 'blood_type', 'medical_condition',
       'date_of_admission', 'doctor', 'hospital', 'insurance_provider',
       'billing_amount', 'room_number', 'admission_type', 'discharge_date',
       'medication', 'test_results'],
      dtype='object')

In [7]:
df.shape

(10000, 15)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                10000 non-null  object
 1   age                 10000 non-null  int64
 2   gender              10000 non-null  object
 3   blood_type          10000 non-null  object
 4   medical_condition   10000 non-null  object
 5   date_of_admission   10000 non-null  object
 6   doctor              10000 non-null  object
 7   hospital            10000 non-null  object
 8   insurance_provider  10000 non-null  object
 9   billing_amount      10000 non-null  float64
 10  room_number         10000 non-null  int64
 11  admission_type      10000 non-null  object
 12  discharge_date      10000 non-null  object
 13  medication          10000 non-null  object
 14  test_results        10000 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 1.1+ MB

In [9]:
!pip install datetime

Collecting datetime
  Downloading DateTime-5.4-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.5/52.5 kB 2.1 MB/s eta 0:00:00
Collecting zope.interface (from datetime)
  Downloading zope.interface-6.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.1/247.1 kB 12.7 MB/s eta 0:00:00
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from datetime) (2023.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from zope.interface->datetime) (67.7.2)
Installing collected packages: zope.interface, datetime
Successfully installed datetime-5.4 zope.interface-6.1

In [10]:
from datetime import timedelta
df['date_of_admission'] = pd.to_datetime(df['date_of_admission'])

df['discharge_date'] = pd.to_datetime(df['discharge_date'])

df['duration_days'] = (df['discharge_date'] - df['date_of_admission']).dt.days
df['duration_days'] = df['duration_days'].astype(int)

df = df.drop(columns = ['date_of_admission', 'discharge_date'], axis = 1)
df.head()

,name,age,gender,blood_type,medical_condition,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,medication,test_results,duration_days
0,Tiffany Ramirez,81,Female,O-,Diabetes,Patrick Parker,Wallace-Hamilton,Medicare,37490.983364,146,Elective,Aspirin,Inconclusive,14
1,Ruben Burns,35,Male,O+,Asthma,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064845,404,Emergency,Lipitor,Normal,14
2,Chad Byrd,61,Male,B-,Obesity,Paul Baker,Walton LLC,Medicare,36874.896997,292,Emergency,Lipitor,Normal,30
3,Antonio Frederick,49,Male,B-,Asthma,Brian Chandler,Garcia Ltd,Medicare,23303.322092,480,Urgent,Penicillin,Abnormal,1
4,Mrs. Brandy Flowers,51,Male,O-,Arthritis,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344184,477,Urgent,Paracetamol,Normal,24

In [11]:
df.isna().sum()

name                  0
age                   0
gender                0
blood_type            0
medical_condition     0
doctor                0
hospital              0
insurance_provider    0
billing_amount        0
room_number           0
admission_type        0
medication            0
test_results          0
duration_days         0
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
df = df.drop(columns = ['room_number', 'name', 'doctor', 'hospital'], axis = 1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   age                 10000 non-null  int64
 1   gender              10000 non-null  object
 2   blood_type          10000 non-null  object
 3   medical_condition   10000 non-null  object
 4   insurance_provider  10000 non-null  object
 5   billing_amount      10000 non-null  float64
 6   admission_type      10000 non-null  object
 7   medication          10000 non-null  object
 8   test_results        10000 non-null  object
 9   duration_days       10000 non-null  int64
dtypes: float64(1), int64(2), object(7)
memory usage: 781.4+ KB

In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [15]:
df['test_results'].value_counts()

Abnormal        3456
Inconclusive    3277
Normal          3267
Name: test_results, dtype: int64

In [17]:
df1 = df.copy()

In [18]:
encoder = LabelEncoder()
df1['test_results'] = encoder.fit_transform(df['test_results'])

In [ ]:
df1['test_results'].value_counts()

0    3456
1    3277
2    3267
Name: test_results, dtype: int64

In [19]:
X = df1.drop(labels = ["test_results"], axis = 1)
y = df1["test_results"]

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [21]:
categorical_cols = []
numerical_cols = []
for col in df1.columns:
    if col != 'test_results':
        if df1[col].dtype == 'object':
            categorical_cols.append(col)
        else:
            numerical_cols.append(col)
print(categorical_cols)
print(numerical_cols)

['gender', 'blood_type', 'medical_condition', 'insurance_provider', 'admission_type', 'medication']
['age', 'billing_amount', 'duration_days']

In [22]:
df1[numerical_cols].describe()

                age  billing_amount  duration_days
count  10000.000000    10000.000000   10000.000000
mean      51.452200    25516.806778      15.561800
std       19.588974    14067.292709       8.612038
min       18.000000     1000.180837       1.000000
25%       35.000000    13506.523967       8.000000
50%       52.000000    25258.112566      16.000000
75%       68.000000    37733.913727      23.000000
max       85.000000    49995.902283      30.000000